name: "Drop-Drop Agent"
description: "Monitor and control outbound network connections with egress filtering"
author: "hanshal101"
branding:
  icon: "shield"
  color: "blue"

inputs:
  allowed-ips:
    description: "List of IPs to allow outbound connections to. By default, only localhost and IPs required for the essential operations of Github Actions are allowed."
    required: false
    default: ""
  allowed-domains:
    description: "List of domains to allow outbound connections to. Wildcards are accepted. For example, if allowing `*.google.com`, this will allow `www.google.com`, `console.cloud.google.com` but not `google.com`. By default, only domains required for essential operations of Github Actions and uploading job summaries are allowed."
    required: false
    default: ""
  dns-policy:
    description: "Controls the policy for DNS requests when `egress-policy` is set to `block`. Options: `allowed-domains-only` (default): Allows DNS requests only for domains specified in `allowed-domains`. `any`: Allows any DNS requests."
    required: false
    default: "allowed-domains-only"
  egress-policy:
    description: "The egress policy to enforce. Valid values are `audit` and `block`. Default: audit"
    required: false
    default: "audit"
  enable-sudo:
    description: "Enable this option to allow steps to execute commands with sudo. This is useful for workflows that require elevated privileges to perform certain tasks. Options: `true` (default) or `false`."
    required: false
    default: "true"
  tetragon-address:
    description: "The address of the Tetragon gRPC server. Default: localhost:54321"
    required: false
    default: "localhost:54321"
  docker-image:
    description: "The Docker image to use for the Drop-Drop agent. Default: hanshal785/drop-drop-agent:latest"
    required: false
    default: "hanshal785/drop-drop-agent:latest"

runs:
  using: "composite"
  steps:
    - name: Setup Drop-Drop Agent (Docker)
      shell: bash
      run: |
        #!/bin/bash
        set -e

        # Check if running on Linux
        if [[ "$RUNNER_OS" != "Linux" ]]; then
          echo "Drop-Drop Agent only supports Linux runners."
          exit 1
        fi

        # Check if running in a container
        if [[ -f "/.dockerenv" ]]; then
          echo "Drop-Drop Agent does not support container-based jobs."
          exit 1
        fi

        # Get Docker image from inputs
        DOCKER_IMAGE="${{ inputs.docker-image }}"

        # Pull the latest Docker image
        echo "Pulling Docker image: $DOCKER_IMAGE"
        docker pull $DOCKER_IMAGE

        # Create temporary directory for logs and configuration
        TEMP_DIR=$(mktemp -d)
        LOG_FILE="$TEMP_DIR/connection_log.json"

        # Configure allowed IPs
        ALLOWED_IPS=""
        if [ -n "${{ inputs.allowed-ips }}" ]; then
          ALLOWED_IPS="${{ inputs.allowed-ips }}"
        fi

        # Configure allowed domains
        ALLOWED_DOMAINS=""
        if [ -n "${{ inputs.allowed-domains }}" ]; then
          ALLOWED_DOMAINS="${{ inputs.allowed-domains }}"
        fi

        # Configure DNS policy
        DNS_POLICY="${{ inputs.dns-policy }}"

        # Configure egress policy
        EGRESS_POLICY="${{ inputs.egress-policy }}"

        # Configure Tetragon address
        TETRAGON_ADDRESS="${{ inputs.tetragon-address }}"

        # Print configuration
        echo "Drop-Drop Agent Configuration:"
        echo "  Firewall Mode: $EGRESS_POLICY"
        echo "  Allowed IPs: $ALLOWED_IPS"
        echo "  Allowed Domains: $ALLOWED_DOMAINS"
        echo "  DNS Policy: $DNS_POLICY"
        echo "  Tetragon Address: $TETRAGON_ADDRESS"
        echo "  Docker Image: $DOCKER_IMAGE"

        # Ensure necessary kernel modules are available
        if ! lsmod | grep -q nfnetlink_queue; then
          echo "Loading nfnetlink_queue module..."
          sudo modprobe nfnetlink_queue || {
            echo "Failed to load nfnetlink_queue module"
            exit 1
          }
        fi

        # Set up iptables rules to redirect traffic to nfqueue
        sudo iptables -I OUTPUT -j NFQUEUE --queue-num 0

        # Start the Docker container with the agent
        echo "Starting Drop-Drop Agent container..."

        # Run the container with necessary privileges and network access
        CONTAINER_ID=$(docker run -d \
          --name drop-drop-agent \
          --cap-add=NET_ADMIN \
          --cap-add=NET_RAW \
          --cap-add=SYS_ADMIN \
          --sysctl net.core.bpf_jit_harden=0 \
          --network=host \
          --pid=host \
          -e FIREWALL_MODE="$EGRESS_POLICY" \
          -e ALLOWED_IPS="$ALLOWED_IPS" \
          -e ALLOWED_DOMAINS="$ALLOWED_DOMAINS" \
          -e DNS_POLICY="$DNS_POLICY" \
          -e TETRAGON_ADDRESS="$TETRAGON_ADDRESS" \
          --entrypoint="/app/agent" \
          $DOCKER_IMAGE \
          --firewall-mode="$EGRESS_POLICY" \
          --allowed-ips="$ALLOWED_IPS" \
          --allowed-domains="$ALLOWED_DOMAINS" \
          --dns-policy="$DNS_POLICY" \
          --tetragon-address="$TETRAGON_ADDRESS" \
          --nfqueue-num=0)

        echo "Container ID: $CONTAINER_ID"

        # Wait briefly to ensure container is running
        sleep 3

        # Check if container is running
        if ! docker ps -q -f id=$CONTAINER_ID | grep -q $CONTAINER_ID; then
          echo "Failed to start Drop-Drop Agent container"
          # Show container logs if possible
          docker logs $CONTAINER_ID 2>&1 || echo "Could not retrieve container logs"
          exit 1
        fi

        # Store the container ID for cleanup
        echo "AGENT_CONTAINER_ID=$CONTAINER_ID" >> $GITHUB_ENV
        echo "AGENT_LOG_FILE=$LOG_FILE" >> $GITHUB_ENV
        echo "AGENT_TEMP_DIR=$TEMP_DIR" >> $GITHUB_ENV

        echo "Drop-Drop Agent container started successfully"

    - name: Cleanup Drop-Drop Agent
      if: always()
      shell: bash
      run: |
        #!/bin/bash
        set -e

        # Stop and remove the agent container if it's running
        if [[ -n "$AGENT_CONTAINER_ID" ]]; then
          echo "Stopping Drop-Drop Agent container (ID: $AGENT_CONTAINER_ID)..."

          # Check if container exists
          if docker ps -a --format "table {{.ID}}" | grep -q $AGENT_CONTAINER_ID; then
            # Stop the container with a timeout
            docker stop -t 10 $AGENT_CONTAINER_ID 2>/dev/null || {
              # Force kill if stop fails
              echo "Force stopping container..."
              docker kill $AGENT_CONTAINER_ID 2>/dev/null || true
            }

            # Remove the container
            docker rm -v $AGENT_CONTAINER_ID 2>/dev/null || true
            echo "Agent container stopped and removed"
          else
            echo "Agent container not found or already removed"
          fi
        fi

        # Remove iptables rules
        sudo iptables -D OUTPUT -j NFQUEUE --queue-num 0 2>/dev/null || true

        # Clean up Docker images if needed (optional cleanup)
        docker image prune -f 2>/dev/null || true

        # Report blocked connections if in audit mode
        if [[ -n "$AGENT_LOG_FILE" ]] && [[ -f "$AGENT_LOG_FILE" ]]; then
          echo "Connection logs:"
          cat "$AGENT_LOG_FILE" || echo "No connection logs found"
        fi

        # Clean up temporary directory
        if [[ -n "$AGENT_TEMP_DIR" ]] && [[ -d "$AGENT_TEMP_DIR" ]]; then
          rm -rf "$AGENT_TEMP_DIR"
        fi

        echo "Drop-Drop Agent cleaned up"
