name: Example Workflow with Drop-Drop

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-check:
    runs-on: ubuntu-latest

    # This action must be the first step to capture all network traffic
    steps:
    - uses: hanshal101/drop-drop@v0.0.0
      with:
        # Run in audit mode to see what connections are made
        egress-policy: audit

        # Optionally specify allowed IPs or domains
        # allowed-domains: |
        #   github.com
        #   api.github.com
        #   objects.githubusercontent.com
        #   *.githubusercontent.com

        # DNS policy controls what DNS requests are allowed
        # dns-policy: allowed-domains-only  # or 'any'

    # Your actual workflow steps
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        npm ci
        # This will show in audit mode what connections are made during installation

    - name: Run tests
      run: |
        npm test
